name: CI Functions

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16.x']

    name: Node ${{ matrix.node }} CI Functions
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: |
            functions/package-lock.json

      - run: npm ci
        working-directory: ./functions
      - run: npm run build
        working-directory: ./functions
