name: CI React

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16.x']

    name: Node ${{ matrix.node }} CI React
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Create empty env file for development build
        run: touch .env
      - name: Restore development environment file content from secret
        env:
          REACT_ENV: ${{ secrets.REACT_ENV }}
        run: echo $REACT_ENV | base64 --decode --ignore-garbage > .env

      - run: npm ci
      - run: npm run build

      - name: Clear env file
        if: always()
        run: rm .env
